### ISSUE TITLE
Not working if url already contains a '?'

### ISSUE THREAD

**Issue by Ahg4goo9** [devattendant/one-page-reader#2]
If I open one of the supported websites via my neewsreader, the heise-URLs often already contain a query parameter, e.g. `https://www.heise.de/news/Bundesregierung-zum-Verbot-der-Deutschen-Welle-Anschlag-auf-die-Pressefreiheit-6350319.html?wt_mc=rss.red.ho.ho.atom.beitrag.beitrag`. The addon then adds `?seite=all` which is ignored, because there is already a question mark. Instead `&` should be used.

**Comment by devattendant** [comment]
Hi,
You're right with the issue. My only idea right now would be to remove all query params at all for these pages and replace them with ?..., as I haven't found a similar solution without rewriting a lot. Do you have a better idea?

**Comment by Ahg4goo9** [comment]
Hi devattentdant,
maybe you could detect an existing question mark. If detected, prepend a `&` in front of the additional query string, if not use a `?`. This should hopefully affect the code not too badly.

**Comment by devattendant** [comment]
You're right, I forgot that the question mark is a reserved character in URLs and therefore cannot be used anywhere else. Version 1.0.4 fixes this issue.
